blank_issues_enabled: false
contact_links:
  - name: ğŸ§ Support Question
    url: https://github.com/laravel/laravel#learning-laravel
    about: This repository is only for reporting bugs. If you need help, click the link on the right.
  - name: ğŸ“š Documentation Issue
    url: https://github.com/laravel/docs
    about: For documentation issues, open a pull request at the laravel/docs repository
